### ISSUE TITLE
The command "dotnet tool restore" exited with code -2147450735

### ISSUE THREAD

**Issue by Webslug** [LubiiiCZ/DevQuickie#2]
I experience the following error when I try to rebuild or run.

The command "dotnet tool restore" exited with code -2147450735.	Quickie015

**Comment by LubiiiCZ** [comment]
Unsufficient info. Sorry.
Are you using VSCode or Visual Studio?
Can you run a blank template project (blue window)?

The project builds and runs fine, the error is probably caused by your dev environment not setup properly.

Please join our discord server and someone will help you investigate: https://discord.gg/UrsNc7Kaz5
